### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by moebiuseye** [jgm/lunamark#10]
Hi. I'm making a PKGBUILD for Archlinux, so that this code is available to AUR users, and my big question is: What is the license I shall put in this file? Custom? Public domain? 

For now, I'm puting "Public domain", because that's what I determined from reading your LICENSE file. 
Anyway, I hope this PKGBUILD works when I'm done.

**Comment by Guard13007** [comment]
(Shouldn't this issue be closed?)
