### ISSUE TITLE
Clarify if utf8.lower is really required.

### ISSUE THREAD

**Issue by daurnimator** [jgm/lunamark#15]
There is only a single `utf8.lower` call in lunamark: https://github.com/jgm/lunamark/blob/master/lunamark/reader/markdown.lua#L51

> Normalize a markdown reference tag.  (Make lowercase, and collapse
> adjacent whitespace characters.)

Does that need to use `utf8.lower`?
If we can remove it, we can drop the dependency on luautf8 and slnunicode.

**Comment by jgm** [comment]
Yes, it's needed.  Reference links are case-insensitive,
and this will break for non-ascii unless we use
utf8.lower.

+++ daurnimator [Apr 19 16 05:00 ]:
