### ISSUE TITLE
lunamark/reader/markdown.lua:150: parse_blocks failed

### ISSUE THREAD

**Issue by TangentFoxy** [jgm/lunamark#16]
Error:

```
/usr/local/share/lua/5.1/lunamark/reader/markdown.lua:150: parse_blocks failed on:
THIS IS A TEST
====
```

Source text:

```
THIS IS A TEST
============

[a link](http://google.com)
```

Same error with following settings all enabled, and all disabled (have not tried other combinations):
- definition_lists
- require_blank_before_blockquote
- require_blank_before_header
- hash_enumerators

Same error:

```
/usr/local/share/lua/5.1/lunamark/reader/markdown.lua:150: parse_blocks failed on:
# This
# is
# a li
```

Different source text:

```
# This
# is
# a list?

## This is a level 2 headr?

This is a header
===============

- list
- with items

[and a link](http://google.com) with *some bold **and italics?** text*

Woo!

> blockquote maybe

Oh yea...maybe.
```

Same options used.

Version: latest on luarocks, 0.4.0-1

**Comment by hollunder** [comment]
I just tried the first example and got no such error. Obvious difference: I was using Lua 5.3.

**Comment by Guard13007** [comment]
I'm trying to use this within OpenResty (LuaJIT, roughly 5.1), so that doesn't help me. Thank you anyhow, if I become desperate, I might try using a separate process running Lua 5.3 to use this. Right now I'm looking into using a different library.

**Comment by craigbarnes** [comment]
@Guard13007 Can you still reproduce this? I remember being able to reproduce it before (a year or so ago), but it works fine for me now with both 5.1 and 5.3.

**Comment by Guard13007** [comment]
@craigbarnes I switched to a different parser (https://luarocks.org/modules/mpeterv/markdown) and then ultimately switched to client-side rendering of Markdown using a JS lib (https://github.com/chjj/marked) so I have not messed with this in a very long time, and to be honest, don't care to try it again.

**Comment by Guard13007** [comment]
If you're curious about my use case, my main website uses Markdown: https://github.com/Guard13007/guard13007.com

That project is in the middle of like two or three major rewrites, so apologies if it is a little confusing right now,

**Comment by craigbarnes** [comment]
> I switched to a different parser (https://luarocks.org/modules/mpeterv/markdown) and then ultimately switched to client-side rendering of Markdown using a JS lib (https://github.com/chjj/marked) so I have not messed with this in a very long time, and to be honest, don't care to try it again.

No worries. I was just wondering if the issue can be closed or not.

**Comment by swift2plunder** [comment]
All tests passed today in 0.5.0-1 with Lua 5.1.
