### ISSUE TITLE
Moving the parsers into a hash table

### ISSUE THREAD

**Issue by Witiko** [jgm/lunamark#24]
I am thinking of moving the parsers in `lunamark/readers/markdown.lua` into a hash table. There is an upper limit of 200 local variables and 60 upvalues in Lua and we are currently hitting both; this should fix the problem.

I am additionally thinking of splitting the hash table into a global one and a local one. The global one would store parsers that do not need to be created more than once, whereas the local one would store parsers whose behavior depends on the options received. I did not profile the code, so this might be a premature optimization, but I would argue that this does not impact the readability / maintainability of the code and I might as well do it, since I am refactoring it all.

So far, I did this for the initial couple of parsers (see <https://github.com/Witiko/markdown/commit/7681cbbba455954963bd400e44e0d2618980d3e4>). Since this will have a huge delta against the current code base and will take quite some time to finish, I would love to hear your thoughts on this.

**Comment by jgm** [comment]
+++ Witiko [Dec 18 16 06:55 ]:
>   I am thinking of moving the parsers in lunamark/readers/markdown.lua
>   into a hash table. There is an upper limit of 200 local variables and
>   60 upvalues in Lua and we are currently hitting both; this should fix
>   the problem.

I imagine there would be a performance impact, since local
variable access is faster, but probably this is the way to
go if the project is to grow.

>   I am additionally thinking of splitting the hash table into a global
>   one and a local one. The global one would store parsers that do not
>   need to be created more than once, whereas the local one would store
>   parsers whose behavior depends on the options received. I did not
>   profile the code, so this might be a premature optimization, but I
>   would argue that this does not impact the readability / maintainability
>   of the code and I might as well do it, since I am refactoring it all.

Don't like the sound of anything "global" but perhaps I've
misunderstood your intent.

**Comment by Witiko** [comment]
> > I am additionally thinking of splitting the hash table into a
> > global one and a local one. […]
>
> Don't like the sound of anything "global" but perhaps I've
> misunderstood your intent.

When I say "global" I mean one that is defined outside the
`M.new` method in `lunamark/readers/markdown.lua`; not
truly global. The advantage is that these parsers need not
be created again at each `M.new` invocation.

**Comment by jgm** [comment]
+++ Witiko [Dec 20 16 14:11 ]:
>     I am additionally thinking of splitting the hash table into a
>     global one and a local one. […]
>
>     Don't like the sound of anything "global" but perhaps I've
>     misunderstood your intent.
>
>   When I say "global" I mean one that is defined outside the
>   M.new method in lunamark/readers/markdown.lua; not
>   truly global. The advantage is that these parsers need not
>   be created again at each M.new invocation.

Okay, that makes sense to me.
