### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by fcambus** [jgm/lunamark#29]
It would be nice if you would consider adding proper source release tarballs,
as GitHub auto-generated tarballs are not immutable. This is an issue [1] for
operating systems creating packages for lunamark. Thanks in advance.

[1] https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by jgm** [comment]
I assume you mean the tarball associated with a particular release,
e.g., https://github.com/jgm/lunamark/archive/0.5.0.tar.gz

In what ways are these not immutable?  Are you claiming that
they sometimes contain something other than the contents of
the 0.5.0 tag?

**Comment by fcambus** [comment]
Yes, I'm talking about the auto-generated tarball associated with a particular release, as you pointed out.

Due to local caches at the GitHub clusters, these files can be different depending on which cluster you're connecting to. We rely on recorded checksum(s) to ensure tarballs have not been tempered with, and this has been a problem in this case.

Basically, if you could fetch https://github.com/jgm/lunamark/archive/0.5.0.tar.gz and upload the downloaded lunamark-0.5.0.tar.gz as a release asset, then this file would be immutable, and we can fetch this file instead.

**Comment by alerque** [comment]
The output of `git archive` has become quite stable, and GitHub has gone to some lengths to make sure they don't change on their platform. The number of cases where this is still an issue are diminutively small, and downloading/uploading the output of a `git archive` is not something I think should be done to compensate. Only in the case where there was an actual source release process should a manually generated source tarball be uploaded.
