### ISSUE TITLE
Discrepancy on option (require_)blank_before_fenced_code_block

### ISSUE THREAD

**Issue by Omikhleia** [jgm/lunamark#38]
- `require_blank_before_fenced_code_block`  in `lunamark/bin/lunamark` (both in help text and in the initial option table)
- `require_blank_before_fenced_code_block` too in the comment block in `lunamark/lunamark/reader/markdown.lua`...

... but later there the code uses `options.blank_before_fenced_code_blocks`

**Comment by Witiko** [comment]
Ah, this would be my mistake. So minor that I also went for it in https://github.com/jgm/lunamark/pull/36. 😉
