### ISSUE TITLE
Fenced div blocks nesting

### ISSUE THREAD

**Issue by Omikhleia** [jgm/lunamark#44]
For recollection and possible future improvement, the `fenced_divs` extension support added in #36 is partial: it is doesn't support nesting of fenced blocks (as it always assumes `:::` as div marker -- For my excuse, I wasn't aware of that possibility, albeit very logical)

For parity with Pandoc, this should be supported, e.g.

```
::: { .diva }
I am in div A

:::: { .divb }
I am in nested div B
::::

Back to div A
:::
```

Generating, e.g. in HTML, something such as:

```
<div class="diva">
    <p>I am in div A</p>
    <div class="divb">
        <p>I am in nested div B</p>
    </div>
    <p>Back to div A</p>
</div>
```
(HTML indented for readability)

**Comment by Witiko** [comment]
Is that right? You reused the fencehead and fencetail functions in your implementation, which should be capable of nesting.

**Comment by Omikhleia** [comment]
Yep, but I am getting, for the above-example:
```
<div class="diva"><p>I am in div A</p>

:::: { .divb } I am in nested div B</div>

<p>Back to div A :::</p>
```
I haven't investigated further (yet).

**Comment by Witiko** [comment]
> I guess I might having fixed it -- the infostring (overlooked, my bad) _and_ the length check (weird, investigating) are both off... I'll need a bit more time to ensure it doesn't introduce other issues and if correct, I'll report my findings/fix in a PR.

That will be much appreciated. I am planning to port fenced divs and bracketed spans to witiko/markdown in https://github.com/Witiko/markdown/pull/207 tomorrow and this seems like something that we will want fixed.
