### ISSUE TITLE
Another fenced div + blockquote edge case (vs. Pandoc)

### ISSUE THREAD

**Issue by Omikhleia** [jgm/lunamark#60]
This doesn't parse as a fenced div:
```
::: {lang=fr}
> Cette citation est en français!
:::
```
Workaround is to have a blank line after the blockquote:
```
::: {lang=fr}
> Cette citation est en français!

:::
```
Pandoc parses the first syntax, though, without issue.

**Comment by Witiko** [comment]
More specifically, lunamark fails to recognize the fenced div, not the blockquote:

```
$ lunamark -Xfenced_divs <<-EOF
::: {lang=fr}
> Cette citation est en français!
:::
EOF
```
``` html
<p>::: {lang=fr}</p>

<blockquote>
<p>Cette citation est en français! :::</p>
</blockquote>
```

This indicates that even though we have added [an exception][1] that allows the end tag (`:::`) to break out of a paragraph, our exception fails to apply for blockquote continuation lines. @Omikhleia, would you like to tackle this?

 [1]: https://github.com/jgm/lunamark/blob/ae3091ad9f0e2cb3cea2571663b2c39e508bf5a7/lunamark/reader/markdown.lua#L1131-L1152
