### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by tarleb** [jgm/lunamark#72]
It seems that the last release was version 0.5.0 in 2016. It would be great if the current version could be installed via luarocks instead of having to build from source.

**Comment by Witiko** [comment]
It would also be nice to have a new release, since there are plenty new features that were added since version 0.5.0. However, I would like to discuss this with @jgm, since they are the author of this repo and they own https://luarocks.org/modules/luarocks/lunamark.

**Comment by tarleb** [comment]
Should we add a GitHub action to push a new version to luarocks each time a new version tag is created? That way, those with push access to the repository could create new releases.

**Comment by jgm** [comment]
I actually don't even remember *how* to make a release.
Looks like the last release on luarocks is 0.3 - 10 years ago.

**Comment by tarleb** [comment]
It's been a while since I made any luarocks release myself, but I found [this page](https://luarocks.org/upload) that seems to have all the answers.

**Comment by Omikhleia** [comment]
Of course, you first have to
 - tag a version on the repository (or make a release)
 - replace "master" with the appropriate tag in the rockspec https://github.com/jgm/lunamark/blob/1c3ed15aa9f32fb7d376371a29deb22e9715d691/lunamark-0.6.0-1.rockspec#L5 
 - and simply upload the rockspec via the link provided by @tarleb

**Comment by alerque** [comment]
Please write a new rockspec file with the new expected tag and *commit it first*, then tag that commit (or something later) as the release. That way the rockspec is included in the source tarball or git clone at the release point, which makes it much easier on downstream packagers than tagging, then adding or changing the rockspec and commiting it in a subsequent commit that one has to fetch separately to get a matching rockspec for the sources.

**Comment by jgm** [comment]
Done!
